version: '3.8'
services:
  quarkus-app:
    build: .
    #bancatoken:latest
    image: unitiva/banca:1.0.0-SNAPSHOT
    ports:
      - 8080:8080
    environment:
     DATABASE_HOST: postgres
     DATABASE_PORT: 5432
     DATABASE_NAME: postgres
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: dev
    depends_on:
      - postgres

  postgres:
    image: postgres
    ports:
      - 6789:5432
    environment:
       POSTGRES_DB: postgresql
       POSTGRES_USER: postgres
       POSTGRES_PASSWORD: dev
