apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kind\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres
  name: postgres
spec:
  ports:
    - name: "6789"
      port: 6789
      targetPort: 5432
  selector:
    io.kompose.service: postgres
status:
  loadBalancer: {}
