apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\kind\kompose.exe convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: quarkus-app
  name: quarkus-app
spec:
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    io.kompose.service: quarkus-app
status:
  loadBalancer: {}
