apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  containers:
    - name: container1
      image: postgres
      ports:
        - containerPort: 5432
      env:
         - name: POSTGRES_DB
           value: postgresql
         - name: POSTGRES_PASSWORD
           value: dev
         - name: POSTGRES_USER
           value: postgres
    - name: container2
      image: 'unitiva/banca:1.0.0-SNAPSHOT'
      ports:
        - containerPort: 9000
      env:
        - name: DATABASE_HOST
          value: postgres
        - name: DATABASE_NAME
          value: postgres
        - name: DATABASE_PORT
          value: '5432'
        - name: POSTGRES_PASSWORD
          value: dev
        - name: POSTGRES_USER
          value: postgres
